# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ff3a5be5b4579a0314499691387c134a"
name = "translate-to-hebrew-app"
handle = "translate-to-hebrew-app"
application_url = "https://bush-orange-reservoir-farmer.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://bush-orange-reservoir-farmer.trycloudflare.com/auth/callback", "https://bush-orange-reservoir-farmer.trycloudflare.com/auth/shopify/callback", "https://bush-orange-reservoir-farmer.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
